name: "sync-plugins"
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  syncPlugins:
    runs-on: ubuntu-latest
    steps:
      - name: Sync plugins 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://dotfyle.com/api/seeder/plugins
          configuration: '{ "method": "GET", "headers": {"Authorization": "${{ secrets.INTERNAL_API_TOKEN }}"} }'
